import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "ql-align-left",
    "ql-align-center",
    "ql-align-right",
    "ql-align-justify",
    "ql-color-red",
    "ql-color-blue",
    "ql-color-green",
    "ql-background-yellow",
    "ql-background-gray",
    "ql-header-1",
    "ql-header-2",
    "ql-header-3",
    "ql-header-4",
    "ql-header-5",
    "ql-header-6",
    "ql-bold",
    "ql-italic",
    "ql-underline",
    "ql-strike",
    "ql-list-ordered",
    "ql-list-bullet",
    "ql-link",
    "ql-image",
    "ql-clean",
  ],
  theme: {
    screens: {
      xs: {
        max: "480px",
      },
      sm: {
        max: "768.98px",
      },
      xlg: {
        max: "976px",
      },
      xmd: {
        max: "1250px",
      },
      md: "768.99px",
      lg: "976px",
      l: "1250px",
      xl: "1440px",
    },

    colors: {
      natural0: "#ffffff",
      natural100: "#F6F8FA",
      natural200: "#E2E4E9",
      natural300: "#CDD0D5",
      natural400: "#868C98",
      natural500: "#525866",
      natural600: "#31353F",
      natural700: "#20232D",
      natural800: "#161922",
      natural900: "#0A0D14",
      blueLighter: "#EBF1FF",
      blueLight: "#C2D6FF",
      blueBase: "#375DFB",
      blueDark: "#253EA7",
      blueDarker: "#162664",
      soft200: "#E2E2E9",
      soft400: "#878698",
      main900: "#0B0A14",
      primaryDark: "#2D9F70",
      primaryBase: "#38C78B",
      white: "#ffffff",
      black: "#000000",
      error: "#df1c36",
      weak100: "#F6F6FA",
      sub500: "#525866",
      sub300: "#CECDD5",
      redBase: "#DF1C36",
      orangeBase: "#F17B2C",
      surface700: "#21202D",
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
